name: Publish Images

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'

jobs:
    changes:
        name: Get changed files
        runs-on: ubuntu-latest
        outputs:
            changed_dirs: ${{ steps.dockerfile_dirs.outputs.all_changed_files }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Get changed dockerfiles
              id: dockerfile_dirs
              uses: tj-actions/changed-files@v45
              with:
                matrix: true
                dir_names: true
                dir_names_exclude_current_dir: true
                files: '**/Dockerfile'
            - name: List dirs
              run: echo '${{ steps.dockerfile_dirs.outputs.all_changed_files }}'

    docker:
        runs-on: ubuntu-latest
        needs: [changes]
        strategy:
            matrix:
                dir: ${{ fromJson(needs.changes.outputs.changed_dirs) }}
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  platforms: linux/amd64,linux/arm64
                  push: true
                  file: ${{ matrix.dir }}/Dockerfile
                  tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.dir }}:latest
