name: Publish Images

on:
  push:
    branches:
      - main
    paths:
      - '**/Dockerfile'

jobs:
    changes:
        name: Get changed files
        runs-on: ubuntu-latest
        outputs:
            changed_dirs: ${{ steps.dockerfile_dirs.outputs.all_changed_files }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Get changed dockerfiles
              id: dockerfile_dirs
              uses: tj-actions/changed-files@v45
              with:
                matrix: true
                dir_names: true
                dir_names_exclude_current_dir: true
                files: '**/Dockerfile'
            - name: List dirs
              run: echo '${{ steps.dockerfile_dirs.outputs.all_changed_files }}'
